name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: piyumika-react-project

      - name: Run tests
        run: npm test
        working-directory: piyumika-react-project

      - name: Build project
        run: npm run build
        working-directory: piyumika-react-project
